import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppConfigProvider from '@app/components/provider/AppConfigProvider';
import AppLayout from '@app/components/layout/AppLayout';
import localFont from 'next/font/local';

// import '@app/styles/reset.css';
import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const droneRanger = localFont({
    src: '../../public/fonts/dronerangerpro_bold.otf',
    variable: '--font-drone-ranger',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${droneRanger.variable} antialiased`}
            >
                <AppConfigProvider>
                    <AppLayout >
                        {children}
                    </AppLayout>
                </AppConfigProvider>
            </body>
        </html>
    );
}
